[workspace]
members = [
    "dynamic_loader",
    "examples/call_arg_offset",
    "examples/call_arg_wrap_offset",
    "examples/cast_call_arg",
    "examples/hello",
    "examples/hello_lib",
    "examples/mutable_ref_test",
    "examples/ptr_arg_use",
    "examples/raw_pointer_mut_test",
    "examples/raw_pointer_test",
    "examples/simple_raw_write",
    "examples/stack_reuse",
    "examples/tag0_call_arg_offset_add_sub",
    "examples/tag0_call_arg_wrapping_offset",
    "examples/tag0_cast_then_call",
    "examples/tag0_copy_chain_then_call",
    "examples/tag0_return_raw_ptr_from_arg",
    "examples/tag0_return_ref_created_in_callee",
    "examples/volatile_ro_rw",
    "instrument-mir",
    "lib_hello",
    "runtime",
]

# Optional but recommended for reproducibility:
resolver = "2"
