[workspace]
members = [
    "dynamic_loader",
    "examples/call_arg_offset",
    "examples/call_arg_offset_add_sub",
    "examples/call_arg_plain_read",
    "examples/call_arg_wrap_offset",
    "examples/cast_call_arg",
    "examples/deref_write_and_read",
    "examples/ext_dep_call/app",
    "examples/ext_dep_call/dep",
    "examples/hello",
    "examples/hello_lib",
    "examples/memcpy_copy_nonoverlapping",
    "examples/memset_write_bytes",
    "examples/mutable_ref_test",
    "examples/plain_write_wrappers",
    "examples/plain_read_wrappers",
    "examples/ptr_arg_use",
    "examples/ptr_arith_add_sub_offset",
    "examples/raw_pointer_mut_test",
    "examples/raw_pointer_test",
    "examples/ret_ptr_basic", "examples/ret_ptr_local",
    "examples/ret_ptr_local_uad",
    "examples/simple_raw_write",
    "examples/stack_reuse",
    "examples/tag0_call_arg_offset_add_sub",
    "examples/tag0_call_arg_wrapping_offset",
    "examples/tag0_cast_then_call",
    "examples/tag0_copy_chain_then_call",
    "examples/tag0_return_raw_ptr_from_arg",
    "examples/tag0_return_ref_created_in_callee",
    "examples/volatile_ro_rw",
    "examples/volatile_wrappers",
    "examples/ret_ptr_local",
    "instrument-mir",
    "lib_hello",
    "runtime",
]

# Optional but recommended for reproducibility:
resolver = "2"
