[package]
name = "instrument-mir"
version = "0.1.0"
edition = "2021"

[package.metadata.rust-analyzer]
rustc_private = true

[dependencies]
# Link your runtime crate automatically
runtime = { path = "../runtime" }

[features]
default = []

[[bin]]
name = "instrument-mir"
path = "src/main.rs"

[[bin]]
name = "cargo-instrument-mir"
path = "src/bin/cargo-instrument-mir.rs"